package cmd

import (
	"fmt"
	"log"
	"os"

	"github.com/fatih/color"
	"github.com/spf13/cobra"
)

var (
	semVer      string
	commitHash  string
	isGitDirty  string
	isSnapshot  string
	goOs        string
	goArch      string
	gitUrl      string
	builtBranch string
	builtDate   string
)

var config tConfig // Holds configuration.

var semReleaseVersion string = semVer +
	func(pre string, txt string) string {
		if len(txt) > 0 {
			return pre + txt
		} else {
			return ""
		}
	}("+", goArch) +
	func(pre string, txt string) string {
		if len(txt) > 0 {
			return pre + txt
		} else {
			return ""
		}
	}(".", builtBranch) +
	func(pre string, txt string) string {
		if len(txt) > 0 {
			return pre + txt
		} else {
			return ""
		}
	}(".", commitHash)

var rootCmd = &cobra.Command{
	Use:               "termos",
	Short:             "Screenshots a terminal output.",
	Long:              `Creates screenshots based on terminal command output.`,
	Version:           semReleaseVersion,
	DisableAutoGenTag: true, // Do not add footer to autogenerated help.

	CompletionOptions: cobra.CompletionOptions{HiddenDefaultCmd: true},

	// Uncomment the following line if your bare application
	// has an action associated with it:
	// Run: func(cmd *cobra.Command, args []string) {},
}

var (
	loggingLevel int         // Global logging level, see MAX_LOGGING_LEVEL.
	logInfo      *log.Logger // Blue logger, for info.
	logWarning   *log.Logger // Yellow logger, for warning.
	logError     *log.Logger // Red logger, for error.
)

// Execute adds all child commands to the root command and sets flags appropriately.
// This is called by main.main(). It only needs to happen once to the rootCmd.
func Execute() {
	err := rootCmd.Execute()
	if err != nil {
		os.Exit(1)
	}
}

func init() {
	initLoggers()
	rootCmd.PersistentFlags().IntVar(&loggingLevel, "logging", 0, // Adding global ie. persistent logging level flag.
		fmt.Sprintf("logging level [0...%d] (default 0)", MAX_LOGGING_LEVEL))

	// Hide help command.
	rootCmd.SetHelpCommand(&cobra.Command{Hidden: true})

	//Do not sort flags.
	rootCmd.Flags().SortFlags = false
}

func initLoggers() {
	hiCyan := color.New(color.FgHiCyan).SprintFunc()
	hiYellow := color.New(color.FgHiYellow).SprintFunc()
	hiRed := color.New(color.FgHiRed).SprintFunc()

	logInfo = log.New(os.Stderr, hiCyan("╭info\n╰"), 0)
	logWarning = log.New(os.Stderr, hiYellow("╭warning\n╰"), 0)
	logError = log.New(os.Stderr, hiRed("╭error\n╰"), 0)
}

/*
checkLogginglevel confirms if logging level does not exceed maximum level.

	loggingLevel = 1 : often
	loggingLevel = 2 : average
	loggingLevel = 3 : seldom

For convenience it also emits some log if loggingLevel >= 1.

	'thisArgs' Values emitted to log.
*/
func checkLogginglevel(thisArgs []string) {
	if loggingLevel > MAX_LOGGING_LEVEL {
		logError.Fatalln(fmt.Errorf("%s", rootCmd.Flag("logging").Usage))
	}

	if loggingLevel >= 1 { // Show info.
		logInfo.Printf("len(args): %d. args: %#v\n", len(thisArgs), thisArgs)
		logInfo.Printf("loggingLevel: %d\n", loggingLevel)
	}
}
